### ISSUE TITLE
Get thumbnail URL over HTTPS.

### ISSUE THREAD

**Issue by joshuapinter** [wistia/wistia-api#17]
Hi there.

I'm getting the thumbnail URL and it's causing my site to complain about insecure content because it goes over HTTP. 

Here's what I'm using: 

```ruby
Wistia::Media.find( wistia_hashed_id ).thumbnail.url

#=> http://embed.wistia.com/deliveries/somehashedid.jpg?image_crop_resized=100x60
```

I tried just adjusting the `http` to `https` but that didn't work. I did some digging and found [here][1] that you need to change `http://embed` to `https://embed-ssl`.

Is there a way to do this so you could simply write: 

```ruby
Wistia::Media.find( wistia_hashed_id ).thumbnail.url( ssl: true )

#=> https://embed-ssl.wistia.com/deliveries/somehashedid.jpg?image_crop_resized=100x60
```

If you want a PR, let me know but it might be an easy fix for you to tackle.

Thanks!

[1]: http://wistia.com/doc/data-api#ssl

**Comment by joshuapinter** [comment]
Ping! :) Any thoughts on this? Thanks!

**Comment by emb78** [comment]
Hi @joshuapinter - thanks for spotting this! We just deployed a change on the endpoint on our side to always return the ssl version of the thumbnail url, so hopefully that does the trick!

**Comment by joshuapinter** [comment]
:clap: Well done! I tested it and it works like a charm. Thanks!
