### ISSUE TITLE
Usage example 

### ISSUE THREAD

**Issue by zohar** [wistia/wistia-api#18]
Can you include a simple example of uploading a video to Wistia from a linux machine?
Something that anyone can copy/change/paste to have their files shot to wistia using this tool.

Thanks in advance...

**Comment by zohar** [comment]
Found this http://wistia.github.io/demobin/magicbox/

**Comment by bschwartz** [comment]
Hey Zohar, glad you found that. The wistia-uploader gem is a bit out of date and we usually recommend people just use curl (http://wistia.com/doc/upload-api#examples). But if it is working for you, that's great!

**Comment by zohar** [comment]
+1 Thanks!
