### ISSUE TITLE
Support for customizations

### ISSUE THREAD

**Issue by rupurt** [wistia/wistia-api#19]
Hi,

Do you have any plans to add support for [customizations](http://wistia.com/doc/data-api#customizations)?

**Comment by freerobby** [comment]
Hi Alex,

This is a nice idea, but we don't have plans to add support for this in the
near-term.

If you have any particular use cases I'd love to hear about them -- always
helpful to have full context when thinking through our roadmap.
robby@wistia.com if that's easier.

--Robby

On Tue, Sep 8, 2015 at 11:27 AM, Alex Kwiatkowski <notifications@github.com>
wrote:

> Hi,
>
> Do you have any plans to add support for customizations
> <http://wistia.com/doc/data-api#customizations>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wistia/wistia-api/issues/19>.
>



-- 
Robby Grossman
Director of Engineering
Wistia
c: 617-909-8431

**Comment by rupurt** [comment]
Ok.

In case anyone else comes across this in the future the way I worked around was 

```ruby
hashed_media_id = "abc123"
path = "/v1/medias/#{hashed_media_id}/customizations.json"
data = { stillUrl: url }.to_json
Wistia::Base.connection.put(path, data)
```

**Comment by nozpheratu** [comment]
*cough*

https://github.com/wistia/wistia-api/pull/15
